Repository anas-elgarhy/aur-release-action, pull requests merged in 2022-11, with the labels that each got.

#1 Add `commit_message` input
  README.md
  action.yml
  entrypoint.sh
Labels: size/M

#2 Fix sed: -e expression #1, char 25: unknown option to `s' issue
  entrypoint.sh
Labels: size/XS

#4 Fix `/entrypoint.sh: line 7: /github/file_commands/set_output_1fdf068c-6a4a-4574-8222-20f2f62907f3: Permission denied` issue
  entrypoint.sh
Labels: size/S

#5 Try fix `/entrypoint.sh: line 7: /github/file_commands/set_output_ff1879e1-cde2-48bb-af48-23c2aecd7c37: Permission denied` issue
  Dockerfile
  entrypoint.sh
Labels: size/S

#6 Remove the outputs :?
  README.md
  action.yml
  entrypoint.sh
Labels: size/S

#7 Fix `/entrypoint.sh: line 83: : command not found` issue
  entrypoint.sh
Labels: size/XS

#8 Fix ` /entrypoint.sh: line 83: generate_commit_message: command not found` issue agin
  Dockerfile
  action.yml
  cred-helper.sh
  entrypoint.sh
  utils.sh
Labels: size/M

#9 Fix
  entrypoint.sh
Labels: size/XS

#10 Fix ` fatal: detected dubious ownership in repository at '/github/workspace'` issue
  entrypoint.sh
Labels: size/XS

#11 Fix git: 'comfig' is not a git command. See 'git --help'. :)
  entrypoint.sh
Labels: size/XS

#13 Fix errors and add a new inputs
  Dockerfile
  action.yml
  entrypoint.sh
  utils.sh
Labels: size/L

#14 Add more docs
  README.md
Labels: size/S

#15 try fix
  entrypoint.sh
Labels: size/S

#16 Try fix Password: su: Authentication token manipulation error issue
  entrypoint.sh
Labels: size/S

#17 Try fix `fatal: detected dubious ownership in repository at '/github/workspace'` issue
  entrypoint.sh
Labels: size/XS

#18 Try fix `cp: cannot create regular file 'archpackage/PKGBUILD': Permission denied` issue
  entrypoint.sh
Labels: size/S

#19 Fix `sudo: commit: command not found` issue
  entrypoint.sh
  utils.sh
Labels: size/XS

#20 Fix fatal: unable to auto-detect email address (got 'root@0075c3f15ef2.(none)') issue
  entrypoint.sh
Labels: size/XS

#21 Try fix fatal: detected dubious ownership in repository at '/github/workspace' issue
  entrypoint.sh
Labels: size/XS

#22 Try fix `fatal: You are not currently on a branch.` issue.
  entrypoint.sh
Labels: size/XS

#23 Try fix issue
  entrypoint.sh
Labels: size/XS

#24 Restuctured & Refactored The Code
  Dockerfile
  entrypoint.sh
  src/build.sh
  src/commit.sh
  src/cred-helper.sh
  src/setup.sh
  src/utils.sh
Labels: enhancement, size/M
